config/routes.rb
Etyme::Application.routes.draw do

  resources :jobs

  match "directory/companies" => "directory#companies", :as=>:directory_companies, :via=>:get
  match "directory/listings" => "directory#listings", :as=>:directory_listings, :via=>:get

  match "directory/individuals" => "directory#individuals", :as=>:directory_individuals, :via=>:get

  match "dashboard" => "home#dashboard", :as=>:dasboard, :via=>:get
  match "dashboard_no_tenant" => "home#dashboard_no_tenant", :as=>:dasboard_no_tenant, :via=>:get
  match "dashboard_tenant" => "home#dashboard_tenant", :as=>:dasboard_tenant, :via=>:get  
  resources :contact_details

  resources :tenant_companies

  authenticated :user do
    root :to => 'home#dashboard'
  end
  root :to => "home#index"
  match "/users/:id/edit_user" => "users#edit_user", :as=>:edit_the_user, :via=>:get
  devise_for :users, :controllers => { :invitations => 'users/invitations' }
  match "/users/:id/update_user" => "users#update_user", :as=>:update_the_user, :via=>:put
  resources :users
end

app/models/tenant_company.rb
class TenantCompany < ActiveRecord::Base
  attr_accessible :about, :name

  attr_accessible :contact_detail_attributes, :phone_attributes, :fax_attributes, :emails_attributes, :im_attributes
  attr_accessible :address_detail_attributes, :addresses_attributes

  belongs_to :owner, :class_name => 'User'
  has_many :jobs

  has_many :assignments, :class_name => 'Job', :as => :customer

  has_many :contact_details, :as => :contactable
  has_many :tenant_users
  has_many :users, :through=>:tenant_users

  has_many :phone, :as => :contactable
  has_many :fax, :as => :contactable
  has_many :emails, :as => :contactable
  has_many :im, :as => :contactable
  has_many :addresses, :as => :contactable

  accepts_nested_attributes_for :phone, :fax, :emails, :addresses, :im
  accepts_nested_attributes_for :contact_details


  def first_phone
    if self.phone.count > 0 then
      self.phone.first.details
    else
      ''
    end
  end
  
  def second_phone
    if self.phone.count > 1 then
      self.phone[1].details
    else
      ''
    end
  end
  
  def third_phone
    if self.phone.count > 2 then
      self.phone[2].details
    else
      ''
    end
  end

  def first_fax
    if self.fax.count > 0 then
      self.fax.first.details
    else
      ''
    end
  end

  def first_email
    if self.email_address.count > 0 then
      self.email_address.first.details
    else
      ''
    end
  end
  
  def second_email
    if self.email_address.count > 1 then
      self.email_address[1].details
    else
      ''
    end
  end
  
  def third_email
    if self.email_address.count > 2 then
      self.email_address[2].details
    else
      ''
    end
  end
  
  def first_address
    if self.addresses.count > 0 then
      address = self.addresses.first
    else
      ''
    end
  end
  
  def second_address
    if self.addresses.count > 1 then
      address = self.addresses[1]
    else
      ''
    end
  end

  def third_address
    if self.addresses.count > 2 then
      address = self.addresses[2]
    else
      ''
    end
  end
  
  def first_im
    if self.im.count > 0 then
      self.im.first.details
    else
      ''
    end
  end
  
  def second_im
    if self.im.count > 1 then
      self.im[1].details
    else
      ''
    end
  end
  
  def third_im
    if self.im.count > 2 then
      self.im[2].details
    else
      ''
    end
  end
  def first_im_kind
    if self.im.count > 0 then
      self.im.first.location
    else
      ''
    end
  end
  
  def second_im_kind
    if self.im.count > 1 then
      self.im[1].location
    else
      ''
    end
  end
  
  def third_im_kind
    if self.im.count > 2 then
      self.im[2].location
    else
      ''
    end
  end
  
  def to_string
    self.name
  end


  scope :by_name, lambda{|search| where('name LIKE ?', search.to_s+'%')}
  scope :not_my_company, lambda{|usr| 
          where('id <> ?', usr.tenant_company.id)  
        }


end

app/controllers/tenant_companies_controller.rb
class TenantCompaniesController < ApplicationController
  # GET /tenant_companies
  # GET /tenant_companies.json
  def index
    @tenant_companies = TenantCompany.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tenant_companies }
    end
  end

  # GET /tenant_companies/1
  # GET /tenant_companies/1.json
  def show
    @tenant_company = TenantCompany.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tenant_company }
    end
  end

  # GET /tenant_companies/new
  # GET /tenant_companies/new.json
  def new
    @tenant_company = TenantCompany.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tenant_company }
    end
  end

  # GET /tenant_companies/1/edit
  def edit
    @tenant_company = TenantCompany.find(params[:id])
  end

  # POST /tenant_companies
  # POST /tenant_companies.json
  def create
    @tenant_company = TenantCompany.new(params[:tenant_company])

    respond_to do |format|
      if @tenant_company.save
        format.html { redirect_to @tenant_company, notice: 'Tenant company was successfully created.' }
        format.json { render json: @tenant_company, status: :created, location: @tenant_company }
      else
        format.html { render action: "new" }
        format.json { render json: @tenant_company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tenant_companies/1
  # PUT /tenant_companies/1.json
  def update
    @tenant_company = TenantCompany.find(params[:id])

    respond_to do |format|
      if @tenant_company.update_attributes(params[:tenant_company])
        format.html { redirect_to @tenant_company, notice: 'Tenant company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tenant_company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tenant_companies/1
  # DELETE /tenant_companies/1.json
  def destroy
    @tenant_company = TenantCompany.find(params[:id])
    @tenant_company.destroy

    respond_to do |format|
      format.html { redirect_to tenant_companies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tenant_companies_helper.rb
module TenantCompaniesHelper
end

app/views/tenant_companies/_form.html.haml
= simple_form_for(@tenant_company, :html=>{:class=>' form-horizontal'}) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name, :input_html=>{:class=>'input-xxlarge'}
    = f.input :about, :input_html=>{:class=>'input-xxlarge', :rows=>6}
    %legend
      Contact Information
    .control-group
      %label.control-label
        Phone
      = f.fields_for(:phone) do|builder|
        - render 'contact_details/phone_fields', :f => builder
          
      .controls
        = link_to_add_contact_detail_fields "Add a phone", f, :phone
    .control-group
      %label.control-label
        Fax
      = f.fields_for(:fax) do|builder|
        - render 'contact_details/fax_fields', :f => builder
      .controls
        = link_to_add_contact_detail_fields "Add a fax", f, :fax
    .control-group
      %label.control-label
        Email
      = f.fields_for(:emails) do|builder|
        - render 'contact_details/email_fields', :f => builder

      .controls
        = link_to_add_contact_detail_fields "Add an Email Address", f, :emails

    .control-group
      %label.control-label
        Internet Messenger
      = f.fields_for(:im) do|builder|
        - render 'contact_details/im_fields', :f => builder
      .controls
        = link_to_add_contact_detail_fields "Add Internet Messenger", f, :im
        
       
    .control-group
      %label.control-label
        Address
      = f.fields_for(:addresses) do|builder|
        - render 'contact_details/address_fields', :f => builder
      .controls
        = link_to_add_address_detail_fields "Add Address", f, :addresses

  .form-actions
    = f.button :submit

app/views/tenant_companies/edit.html.haml
%h1 Editing Company

= render 'form'

= link_to 'Show', @tenant_company
\|
= link_to 'Back', tenant_companies_path

app/views/tenant_companies/index.html.haml
%h1 Listing tenant_companies

%table
  %tr
    %th Name
    %th About
    %th
    %th
    %th

  - @tenant_companies.each do |tenant_company|
    %tr
      %td= tenant_company.name
      %td= tenant_company.about
      %td= link_to 'Show', tenant_company
      %td= link_to 'Edit', edit_tenant_company_path(tenant_company)
      %td= link_to 'Destroy', tenant_company, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Tenant company', new_tenant_company_path

app/views/tenant_companies/new.html.haml
%h1 New tenant_company

= render 'form'

= link_to 'Back', tenant_companies_path

app/views/tenant_companies/show.html.haml
%p#notice= notice
- content_for(:title) do
  - "Company::"+@tenant_company.name 

.row
  .span8
    %h3
      =@tenant_company.name

  .span4
    .well
      = link_to 'Edit', edit_tenant_company_path(@tenant_company), :class=>'btn'
      -# link_to 'Back', companies_path, :class=>'btn'
    - @contact = @tenant_company
    = render :partial=>'contact_details/contact_details', :local=>{:contact=>@tenant_company}
    
    - if !@tenant_company.about.blank? then
      %hr
      %p
        %b 
          ='About '+@tenant_company.name.to_s
      = @tenant_company.about
    - if @tenant_company.users.count > 0
      %hr
      %p
        %b
          People who work here
      %table.table
        - @tenant_company.users.each do |one_individual|
          %tr
            %td
              = link_to one_individual.name.to_s, one_individual
              %br
              %small
                =one_individual.role_name