config/routes.rb
Etyme::Application.routes.draw do

  resources :jobs

  match "directory/companies" => "directory#companies", :as=>:directory_companies, :via=>:get
  match "directory/listings" => "directory#listings", :as=>:directory_listings, :via=>:get

  match "directory/individuals" => "directory#individuals", :as=>:directory_individuals, :via=>:get

  match "dashboard" => "home#dashboard", :as=>:dasboard, :via=>:get
  match "dashboard_no_tenant" => "home#dashboard_no_tenant", :as=>:dasboard_no_tenant, :via=>:get
  match "dashboard_tenant" => "home#dashboard_tenant", :as=>:dasboard_tenant, :via=>:get  
  resources :contact_details

  resources :tenant_companies

  authenticated :user do
    root :to => 'home#dashboard'
  end
  root :to => "home#index"
  match "/users/:id/edit_user" => "users#edit_user", :as=>:edit_the_user, :via=>:get
  devise_for :users, :controllers => { :invitations => 'users/invitations' }
  match "/users/:id/update_user" => "users#update_user", :as=>:update_the_user, :via=>:put
  resources :users
end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :name, :description, :customer_name, :tenant_company_id, :customer_id, :customer_type
  belongs_to :tenant_company
  belongs_to :customer, :polymorphic => true

  def customer_name=(name)
   @customer_name = name
  end
    
  def customer_name()
	  if self.customer_id!= nil then
	    self.customer_name = self.customer.name
	  end
	  @customer_name
  end

  def belongs_to_current_user_company?(usr)
  	if usr.tenant_company == nil then
  		false
		else
	  	self.tenant_company == usr.tenant_company
  	end
  end

  scope :by_tenant_company, lambda{|tenant_company| where(:tenant_company_id=> tenant_company.id)}
  scope :by_customer, lambda{|customer| where('customer_id = ? AND customer_type = ?', customer.id, customer.class.name)}
  scope :not_by_tenant_company, lambda{|tenant_company| where(Job.arel_table[:tenant_company_id].not_eq(tenant_company.id))}
  scope :not_by_customer, lambda{|customer| where('customer_id <> ? AND customer_type <> ?', customer.id, customer.class.name)}
  
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @job = Job.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(params[:job])
    @job.tenant_company_id = current_user.tenant_company.id

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.haml
= simple_form_for(@job,  :html=>{:class=>' form-horizontal'}) do |f|
  = f.error_notification

  .form-inputs
    %legend
      Customer
    = f.input :customer_name, :input_html=>{:class=>'input-xxlarge'}, :hint=>'Who is the customer? Type and select...', :label=>false
    = f.input :customer_id, :as=>:hidden
    = f.input :customer_type, :as=>:hidden
    %legend
      Job Details

    = f.input :name, :input_html=>{:class=>'input-xxlarge'}, :label=>'Job Title', :hint=>'Define the job in one sentence'
    = f.input :city, :input_html=>{:class=>'input-xxlarge'}, :label=>'City', :hint=>'Location(City)'
    = f.input :state, :input_html=>{:class=>'input-xxlarge'}, :label=>'State'
    = f.input :zip, :input_html=>{:class=>'input-xxlarge'}, :label=>'Zip'
    = f.input :start_date, :input_html=>{:class=>'input-xlarge datepicker'}
    = f.input :salary, :input_html=>{:class=>'input-xlarge'}
    = f.input :duration, :input_html=>{:class=>'input-xlarge'}
    = f.input :type, :as=>:select, :collection=>['H (Hire)', 'C2H (Contract to Hire)', 'C (Contract)', 'FL (FreeLance)'], :input_html=>{:class=>'input-xlarge '}
    = f.input :openings, :as=>:select, :collection=>1..20, :input_html=>{:class=>'input-xlarge '}
    = f.input :remaining_openings, :as=>:select, :collection=>1..20, :input_html=>{:class=>'input-xlarge '}
    = f.input :company_job_id, :input_html=>{:class=>'input-xlarge '}
    = f.input :category, :input_html=>{:class=>'input-xlarge '}
    %legend
      Description

    = f.input :description, :input_html=>{:class=>'input-xxlarge'}, :hint=>'Add more details for the job', :label=>false

  .form-actions
    = f.button :submit

:javascript
$(function(){
  
  $("#job_customer_name" ).autocomplete({
      source: "/directory/listings",  
      minLength: 2,
      focus: function( event, ui ) {
        $(this).val($(this).val());
        return false;
      },
      select: function(event, ui) {
        
        $('#job_customer_name').val(ui.item.name);
        
        $('#job_customer_id').val(ui.item.id);
        $('#job_customer_type').val(ui.item.type);

        return false;
      },
    }).data("ui-autocomplete")._renderItem = function( ul, item ) {
      console.log(item);
      return $( "<li></li>" ).data( "item.autocomplete", item )
          .append( "<a>"+(item.type=='User'?'<i class="icon-user" />':'<i class="icon-plus" />')+"<b>" + item.name + "</b><br/>" + item.details + "</a>" )
          .appendTo( ul );
    };

})

app/views/jobs/_mini_job.html.haml
%tr
  %td
    = link_to @job.name, @job
  %td
    = time_ago_in_words(@job.created_at)

app/views/jobs/edit.html.haml
%h1 Editing job

= render 'form'

= link_to 'Show', @job
\|
= link_to 'Back', jobs_path

app/views/jobs/index.html.haml
.row
  .span8
    %h1 Jobs Market
  
    %table.table
      %tr
        %th Name
        %th
        %th
        %th

      - @jobs.each do |job|
        %tr
          %td= job.name
          %td= link_to 'Show', job
          %td= link_to 'Edit', edit_job_path(job)
          %td= link_to 'Destroy', job, :method => :delete, :data => { :confirm => 'Are you sure?' }
    =paginate @jobs
  .span4
    - if current_user.can_create_new_job? then
      = link_to 'New Job', new_job_path


%br

app/views/jobs/new.html.haml
%h1 New job

= render 'form'

= link_to 'Back', jobs_path

app/views/jobs/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @job.name

= link_to 'Edit', edit_job_path(@job)
\|
= link_to 'Back', jobs_path