config/routes.rb
Etyme::Application.routes.draw do

  resources :jobs

  match "directory/companies" => "directory#companies", :as=>:directory_companies, :via=>:get
  match "directory/listings" => "directory#listings", :as=>:directory_listings, :via=>:get

  match "directory/individuals" => "directory#individuals", :as=>:directory_individuals, :via=>:get

  match "dashboard" => "home#dashboard", :as=>:dasboard, :via=>:get
  match "dashboard_no_tenant" => "home#dashboard_no_tenant", :as=>:dasboard_no_tenant, :via=>:get
  match "dashboard_tenant" => "home#dashboard_tenant", :as=>:dasboard_tenant, :via=>:get  
  resources :contact_details

  resources :tenant_companies

  authenticated :user do
    root :to => 'home#dashboard'
  end
  root :to => "home#index"
  match "/users/:id/edit_user" => "users#edit_user", :as=>:edit_the_user, :via=>:get
  devise_for :users, :controllers => { :invitations => 'users/invitations' }
  match "/users/:id/update_user" => "users#update_user", :as=>:update_the_user, :via=>:put
  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify # :before_add => :remove_current_roles
  
  before_create :remove_tenant_if_company_name_not_provided, :create_the_tenant_if_company_name_provided
  before_save :invitee_company_take_precednece_if_user_is_invited
  after_create :assign_moderator_role_if_owner_of_company
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :invitable

  # Setup accessible (or protected) attributes for your model
  #attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  has_one :owned_tenant_company, :class_name => 'TenantCompany', :foreign_key => :owner_id
  has_one :tenant_user
  has_one :tenant_company, :through => :tenant_user

  attr_accessible :contact_detail_attributes, :phone_attributes, :fax_attributes, :emails_attributes, :im_attributes, :role_ids
  attr_accessible :address_detail_attributes, :addresses_attributes, :role_name, :owned_tenant_company_name, :tenant_user_attributes

  has_many :contact_details, :as => :contactable
  
  has_many :phone, :as => :contactable
  has_many :fax, :as => :contactable
  has_many :emails, :as => :contactable
  has_many :im, :as => :contactable
  has_many :addresses, :as => :contactable

  has_many :jobs, :as => :customer


  accepts_nested_attributes_for :phone, :fax, :emails, :addresses, :im
  accepts_nested_attributes_for :contact_details, :tenant_company


  def can_create_new_job? 
    # for now if you have a company you can create a job
    self.belongs_to_a_company?
  end
  def is_invited_and_registering_first_time
    !self.invited_by.blank? && self.sign_in_count == 0
  end

  def invitee_company_take_precednece_if_user_is_invited
    # is this guy invited to begin with and thsi is his first time registering?
    if self.is_invited_and_registering_first_time then
      # he is invited so it means if he has entered the name of any tenant company it shoudl be nullified
      self.owned_tenant_company_name = nil
    end
  end

  def belongs_to_a_company?
    self.tenant_company!= nil
  end

  def current_tenant_company_name
    if self.tenant_company!= nil then
      self.tenant_company.name
    else
      'Etyme'
    end
  end

  def actual_current_tenant_company_name
    if self.tenant_company!= nil then
      self.tenant_company.name
    else
      false
    end
  end


  def owned_tenant_company_name=(name)
    @owned_tenant_company_name = name
    if !self.is_invited_and_registering_first_time
      self.owned_tenant_company = TenantCompany.new(:name=>name)
    end
  end

  def owned_tenant_company_name
    @owned_tenant_company_name
  end  

  def assign_moderator_role_if_owner_of_company
    # check was the user ever invited
    if self.invited_by.blank? # this guy was never invited so assume he has created the company if it exists
      if self.owned_tenant_company == nil  then
        self.add_role :user
        self.save
      else
        self.add_role :owner
        self.tenant_company = self.owned_tenant_company
        self.save
      end
    end
  end

  def create_the_tenant_if_company_name_provided
    # check is the user already associated with a tenant
    if self.tenant_company == nil || self.invited_by.blank? then # no tenant
      if !self.owned_tenant_company_name.blank? then
        self.owned_tenant_company.save
      end
    else
      self.owned_tenant_company = nil
    end

  end

  def remove_tenant_if_company_name_not_provided
    if self.owned_tenant_company_name.blank? || self.is_invited_and_registering_first_time then
      self.owned_tenant_company = nil
    end
  end

  def role_name
    role = self.roles.first
    if role!=nil then
      role.name
    else
      ''
    end
  end

  scope :accessible_records, lambda {|usr| 
    if !usr.has_role? :admin
      joins(:tenant_user).where('tenant_users.tenant_company_id = ?', usr.tenant_company.id)  
    end
  } 

  scope :by_name, lambda{|search| where('name LIKE ?', search.to_s+'%')}
  scope :not_my_collegues, lambda{|usr| 
          joins(:tenant_user).where('tenant_users.tenant_company_id <> ?', usr.tenant_company.id)  
        }
end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController
    # GET /resource/invitation/new
  def new
    build_resource
    render 'users/invitations/invitations/new'
  end

  # POST /resource/invitation
  def create
    self.resource = resource_class.invite!(resource_params, current_inviter)

    if resource.errors.empty?
      set_flash_message :notice, :send_instructions, :email => self.resource.email
	
	    self.resource.tenant_company = current_user.tenant_company
	    self.resource.save

      respond_with resource, :location => after_invite_path_for(resource)
    else
      respond_with_navigational(resource) {     render 'users/invitations/invitations/new' }
    end
  end

  # GET /resource/invitation/accept?invitation_token=abcdef
  def edit
    render :edit
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_filter :authenticate_user!
  load_and_authorize_resource

  def index
    #authorize! :index, @user, :message => 'Not authorized as an administrator.'

    @users = User.accessible_records(current_user).page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end
 
  def edit_user
    @user = User.find(params[:id])
  end
  
  def update_user
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User Details updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/views/users/_form.html.haml
= simple_form_for(@user,:url=>update_the_user_path(@user),  :html=>{:class=>' form-horizontal'}) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name, :input_html=>{:class=>'input-xxlarge'}
    %legend
      Contact Information
    .control-group
      %label.control-label
        Phone
      = f.fields_for(:phone) do|builder|
        - render 'contact_details/phone_fields', :f => builder
          
      .controls
        = link_to_add_contact_detail_fields "Add a phone", f, :phone
    .control-group
      %label.control-label
        Fax
      = f.fields_for(:fax) do|builder|
        - render 'contact_details/fax_fields', :f => builder
      .controls
        = link_to_add_contact_detail_fields "Add a fax", f, :fax
    .control-group
      %label.control-label
        Email
      = f.fields_for(:emails) do|builder|
        - render 'contact_details/email_fields', :f => builder

      .controls
        = link_to_add_contact_detail_fields "Add an Email Address", f, :emails

    .control-group
      %label.control-label
        Internet Messenger
      = f.fields_for(:im) do|builder|
        - render 'contact_details/im_fields', :f => builder
      .controls
        = link_to_add_contact_detail_fields "Add Internet Messenger", f, :im
        
       
    .control-group
      %label.control-label
        Address
      = f.fields_for(:addresses) do|builder|
        - render 'contact_details/address_fields', :f => builder
      .controls
        = link_to_add_address_detail_fields "Add Address", f, :addresses

  .form-actions
    = f.button :submit

app/views/users/_user.html.haml
.modal{:id => "role-options-#{user.id}", :style => "display: none;"}
  = simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f|
    .modal-header
      %a.close{"data-dismiss" => "modal"} ×
      %h3 Change Role
    .modal-body
      = f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first
    .modal-footer
      = f.submit "Change Role", :class => "btn"
      %a.btn{"data-dismiss" => "modal", :href => "#"} Close

app/views/users/edit_user.html.haml
%h1 Editing User

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
.row
  .span8
    %h3 
      Users
    %table.table.table-condensed
      %thead
        %tr
          %th Username
          %th Email
          %th Registered
          %th Role
          %th
          %th
      %tbody
        - @users.each do |user|
          %tr
            %td= link_to user.name, user
            %td= user.email
            %td= user.created_at.to_date
            %td= user.roles.first.name.titleize unless user.roles.first.nil?
            %td
              %a.btn.btn-mini{"data-toggle" => "modal", :href => "#role-options-#{user.id}", :type => "button"} Change role
              = render user
            %td= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user
    = paginate @users  
  .span4
    .well
      = link_to 'Add new user', new_user_invitation_path,class: 'btn btn-primary'

app/views/users/show.html.haml
%p#notice= notice

.row
  .span8
    %h3
      =@user.name
  .span4
    .well
      = link_to 'Edit', edit_the_user_path(@user), :class=>'btn'
      -# link_to 'Back', companies_path, :class=>'btn'
    - @contact = @user
    = render :partial=>'contact_details/contact_details', :local=>{:contact=>@user}
    