config/routes.rb
Etyme::Application.routes.draw do

  resources :jobs

  match "directory/companies" => "directory#companies", :as=>:directory_companies, :via=>:get
  match "directory/listings" => "directory#listings", :as=>:directory_listings, :via=>:get

  match "directory/individuals" => "directory#individuals", :as=>:directory_individuals, :via=>:get

  match "dashboard" => "home#dashboard", :as=>:dasboard, :via=>:get
  match "dashboard_no_tenant" => "home#dashboard_no_tenant", :as=>:dasboard_no_tenant, :via=>:get
  match "dashboard_tenant" => "home#dashboard_tenant", :as=>:dasboard_tenant, :via=>:get  
  resources :contact_details

  resources :tenant_companies

  authenticated :user do
    root :to => 'home#dashboard'
  end
  root :to => "home#index"
  match "/users/:id/edit_user" => "users#edit_user", :as=>:edit_the_user, :via=>:get
  devise_for :users, :controllers => { :invitations => 'users/invitations' }
  match "/users/:id/update_user" => "users#update_user", :as=>:update_the_user, :via=>:put
  resources :users
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
- if user_signed_in?
  = link_to root_path, :class => 'brand' do
    = current_user.current_tenant_company_name
    %sup
      Etymified
-else
  = link_to "Etyme", root_path, :class => 'brand'
%ul.nav
  - if user_signed_in?
    %li
      = link_to 'Job Market', jobs_path 
    %li
      = link_to 'Directory', directory_individuals_path 
    %li
      = link_to 'Team', users_path 
  - else
    %li
      = link_to 'Login', new_user_session_path
- if user_signed_in?
  .pull-right
    %ul.nav.pull-right
      %li
        .dropdown
          .btn-group
            %a.btn.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              = "Hi #{ current_user.name || current_user.username }"
              %span.caret
            %ul.dropdown-menu
              %li
                = link_to users_path do
                  %i.icon-user
                  Users
                %li.divider
              %li
                = link_to edit_user_registration_path do
                  %i.icon-ribbon
                  Edit Account
              %li
                = link_to edit_the_user_path(current_user) do
                  %i.icon-pencil
                  Edit My Profile
              - if current_user.has_role? :owner then
                %li
                  = link_to edit_tenant_company_path(current_user.tenant_company) do
                    %i.icon-edit
                    Edit My Company
              - if current_user.belongs_to_a_company? then
                %li
                  = link_to tenant_company_path(current_user.tenant_company) do
                    %i.icon-eye-open
                    My Company Profile
              
              %li.divider
              %li
                = link_to destroy_user_session_path, :method=>'delete' do
                  %i.icon-eject
                  Logout

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Etyme"
      %meta{:content => content_for?(:description) ? yield(:description) : "Etyme", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    .navbar.navbar-fixed-top.navbar-inverse
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .row
          .span12
            = render 'layouts/messages'
            = yield
          %footer
      / ! end of .container
    / ! end of #main